config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get "about" => "public/homes#about"

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  scope module: :public do
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    # 退会確認画面
    get "customers/unsubscribe" => "customers#unsubscribe"
    # 論理削除用のルーティング
    patch "customers/withdraw" => "customers#withdraw"

    get "search" => "items#search"
    resources :items, only: [:index, :show]

    resources :addresses, only: [:index, :create, :update, :destroy, :edit]

    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]

    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "/" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]

    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price #消費税を求めるメソッド
    (price*1.1).floor
  end

  def self.search(search)
    if search
      Item.where(['name LIKE ?', "%#{search}%"])
    else
      Item.all
    end
  end

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion:{in: [true, false]}

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def index
    @items = Item.order(id:"DESC").page(params[:page])
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :image, :genre_id)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 my-5">
    <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3">商品編集</h4>
    </div>
  </div>

  <% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <div class="row-error">
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group row">
    <div class="col-8 mx-auto">
      <%= form_with model: @item, url:admin_item_path(@item.id), method: :patch do |f| %>
        <div class="row" >
          <div class="col-3">
          <label for="itemImage">商品画像</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.file_field :image, accept: "image/*"%>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemName">商品名</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.text_field :name, placeholder: "商品名", style: "width:100%;" %>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemintroduction">商品説明</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", style: "width:100%;" %>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemGenre">ジャンル</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "　　　--選択してください--　　　　", style: "width:100%;" %>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemPrice">税抜価格</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.text_field :price, placeholder: "1000", style: "width:100%;" %>
          </div>
          <span>円</span>
        </div>
        <div class="row">
          <div class="col-3">
          <label for="itemStatus">販売ステータス</label>
          </div>
          <div class="col-5 mb-3 mb-2">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中" %>

            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中" %>
          </div>
        </div>
        <div class="row">
        <div class="col-4 mx-auto">
          <%= f.submit '変更を保存', class: "btn btn-success font-weight-bold px-4" %>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 mt-5 mb-2">
      <div class="main-text mb-5">
        <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3">商品一覧</h4>
        <div class="new-button">
          <button type="button" class="btn btn-light rounded-circle p-0 shadow mb-5 bg-white rounded font-weight-bold" style="width:3rem;height:3rem;">
            <a href= "/admin/items/new", style="text-decoration: none;"><strong>＋</strong></a>
          </button>
        </div>
      </div>

    <table class="table mx-auto">
      <thead style="background-color: #F5F5F5;">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
             <span><%= item.name %></span>
            <% end %>
          </td>
          <td><%= item.price.to_s(:delimited) %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
              <span style="color: green;", class= "font-weight-bold">販売中</span>
            <% else %>
              <span style="color: #C0C0C0;", class= "font-weight-bold">販売停止中</span>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
    </div>

    <div class="col mx-auto">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 my-5">
    <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3">商品新規登録</h4>
    </div>
  </div>

  <% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <div class="row-error">
    <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group row">
    <div class="col-8 mx-auto">
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
        <div class="row" >
          <div class="col-3">
          <label for="itemImage">商品画像</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.file_field :image, accept: "image/*"%>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemName">商品名</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.text_field :name, placeholder: "商品名", style: "width:100%;" %>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemintroduction", class=>商品説明</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", style: "width:100%;" %>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemGenre">ジャンル</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, :prompt => "　　　--選択してください--　　　　", style: "width:100%;" %>
          </div>
        </div>
        <div class="row" >
          <div class="col-3">
          <label for="itemPrice">税抜価格</label>
          </div>
          <div class="col-5 mb-2">
          <%= f.text_field :price, placeholder: "1000", style: "width:100%;" %>
          </div>
          <span>円</span>
        </div>
        <div class="row">
          <div class="col-3">
          <label for="itemStatus">販売ステータス</label>
          </div>
          <div class="col-5 mb-3 mb-2">
            <%= f.radio_button :is_active, "ture", checked: true %>
            <%= f.label :is_active, "販売中" %>

            <%= f.radio_button :is_active, "false" %>
            <%= f.label :is_active, "販売停止中" %>
          </div>
        </div>
        <div class="row">
        <div class="col-4 mx-auto">
          <%= f.submit '新規登録', class: "btn btn-success font-weight-bold px-4" %>
        </div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 my-5">
    <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3">商品詳細</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-4">
      <%= image_tag @item.get_image(300,500) %>
    </div>
    <table class="col-3">
      <tbody>
        <tr>
          <td class= "pb-3">商品名</td>
          <td class= "pb-3"><%= @item.name %></td>
        </tr>
        <tr>
          <td class= "pb-3">商品説明</td>
          <td class= "pb-3"><%= @item.introduction %></td>
        </tr>
        <tr>
          <td class= "pb-3">ジャンル</td>
          <td class= "pb-3"><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td class= "pb-3">税込価格<br>(税抜価格)</td>
          <td class= "pb-3"><%= (@item.price*1.1).floor.to_s(:delimited) %>（<%= @item.price.floor.to_s(:delimited)*1.1 %>）円</td>
        </tr>
        <tr>
          <td class= "pb-3">販売ステータス</td>
          <td class= "pb-3">
            <% if @item.is_active %>
              <span style="color: green;", class= "font-weight-bold">販売中</span>
            <% else %>
              <span style="color: #C0C0C0;", class= "font-weight-bold">販売停止中</span>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-2 mx-auto">
      <%= link_to '編集する', edit_admin_item_path, class: "btn btn-success font-weight-bold px-4" %>
    </div>
  </div>
</div>