config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"
  get "about" => "public/homes#about"

  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  scope module: :public do
    get "customers/my_page" => "customers#show"
    get "customers/information/edit" => "customers#edit"
    patch "customers/information" => "customers#update"
    # 退会確認画面
    get "customers/unsubscribe" => "customers#unsubscribe"
    # 論理削除用のルーティング
    patch "customers/withdraw" => "customers#withdraw"

    get "search" => "items#search"
    resources :items, only: [:index, :show]

    resources :addresses, only: [:index, :create, :update, :destroy, :edit]

    delete "cart_items/destroy_all" => "cart_items#destroy_all"
    resources :cart_items, only: [:index, :create, :update, :destroy]

    post "orders/confirm" => "orders#confirm"
    get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :index, :create, :show]
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "/" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]

    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :is_deleted, inclusion:{in: [true, false]}

  validates :email, uniqueness: true

  def active_for_authentication?
    super && (is_deleted == false)
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.order(id:"DESC").page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :telephone_number, :address, :is_deleted, :postal_code)
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 my-5">
      <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
    </div>
  </div>

  <% if @customer.errors.any? %>
  <%= @customer.errors.count %>件のエラーが発生しました
  <div class="row-error">
    <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group col-11 mx-auto mb-4">
    <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
    <table class="field">
      <tbody>
        <tr class="main-form">
          <td class="main-item">会員ID</td>
          <td><%= @customer.id %></td>
          <td></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">氏名</td>
          <td class="main-item"><%= f.text_field :last_name, class: "form-control" %></td>
          <td><%= f.text_field :first_name, class: "form-control" %></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">フリガナ</td>
          <td class="main-item"><%= f.text_field :last_name_kana, class: "form-control" %></td>
          <td><%= f.text_field :first_name_kana, class: "form-control" %></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">郵便番号</td>
          <td class="main-item"><%= f.text_field :postal_code, class: "form-control" %></td>
          <td></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">住所</td>
          <td colspan="2"><%= f.text_field :address, class: "form-control" %></td>
          <td></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">電話番号</td>
          <td class="main-item"><%= f.text_field :telephone_number, class: "form-control" %></td>
          <td></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">メールアドレス</td>
          <td class="main-item"><%= f.email_field :email, class: "form-control" %></td>
          <td></td>
        </tr>
        <tr class="main-form">
          <td class="main-item">会員ステータス</td>
          <td class="main-item">
            <h5>
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, "有効" %>
              <span>　</span>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会" %>
            </h5>
          </td>
          <td></td>
        </tr>
        <tr class="main-form">
          <td></td>
          <td><%= f.submit '変更を保存', class: "btn btn-success font-weight-bold px-4 btn-lg" %></td>
          <td></td>
        </tr>
      </tbody>
    <% end %>
    </table>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 my-5">
      <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3">会員一覧</h4>
    </div>
  </div>

  <div class="row">
    <table class="table col-9 mx-auto">
      <thead style="background-color: #F5F5F5;">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
             <span><%= customer.last_name %><%= customer.first_name %></span>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_deleted != true %>
              <span style="color: green;", class= "font-weight-bold">有効</span>
            <% else %>
              <span style="color: #C0C0C0;", class= "font-weight-bold">退会</span>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-2 mx-auto">
    <%= paginate @customers %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-7 my-5">
      <h4 style="background-color: #F5F5F5;", class="d-inline-flex px-3"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
    </div>
  </div>

  <div class="row">
    <table class="col-7">
      <tbody>
        <tr>
          <td class= "pb-3">会員ID</td>
          <td class= "pb-3"><%= @customer.id %></td>
        </tr>
        <tr>
          <td class= "pb-3">氏名</td>
          <td class= "pb-3"><%= @customer.last_name %>　<%= @customer.first_name %></td>
        </tr>
        <tr>
          <td class= "pb-3">フリガナ</td>
          <td class= "pb-3"><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <td class= "pb-3">郵便番号</td>
          <td class= "pb-3"><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <td class= "pb-3">住所</td>
          <td class= "pb-3"><%= @customer.address %></td>
        </tr>
        <tr>
          <td class= "pb-3">電話番号</td>
          <td class= "pb-3"><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <td class= "pb-3">メールアドレス</td>
          <td class= "pb-3"><%= @customer.email %></td>
        </tr>
        <tr>
          <td class= "pb-3">退会ステータス</td>
          <td class= "pb-3">
            <% if @customer.is_deleted != true %>
              <span style="color: green;", class= "font-weight-bold">有効</span>
            <% else %>
              <span style="color: #C0C0C0;", class= "font-weight-bold">退会</span>
            <% end %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td>
            <div class="row">
            <div class="col-4">
              <%= link_to '編集する', edit_admin_customer_path, class: "btn btn-success font-weight-bold px-4 btn-sm" %>
            </div>
            <div class="col-6">
              <%= link_to '注文履歴一覧を見る', admin_path, class: "btn btn-primary font-weight-bold px-4 btn-sm" %>
            </div>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>